### ISSUE TITLE
Request - Example with picture upload

### ISSUE THREAD

**Issue by edel79** [cjrasmussen/BlueskyApi#1]
Hello, thank you for this peace of code, usefull ti me.
It would be more, with a working sample of how to upload a picture and then attach it to the post to publish.

Here is the theorical way of doing it: https://atproto.com/blog/create-post#images-embeds

Thanks in advance :)

**Comment by cjrasmussen** [comment]
Dropped that particular example into the README but I'm not looking for this to become documentation for how to do everything Bsky can do.  I do have some examples in a blog post: https://cjr.dev/2023/07/04/php-and-the-bluesky-api/.

**Comment by edel79** [comment]
Thank you for that. I'm new to the AT protocol so this will be very helpful to me.
