### ISSUE TITLE
Fatal error: $apiKey must not be accessed before initialization

### ISSUE THREAD

**Issue by jaybeaton** [cjrasmussen/BlueskyApi#10]
I set up a process where my code would:

1. Try to refresh the session with a refresh token.
2. If that failed, try to start a new session with the handle and password.

I was testing what would happen if a refresh token existed but was invalid and got this error:

```
Fatal error: Uncaught Error: Typed property cjrasmussen\BlueskyApi\BlueskyApi::$apiKey must not 
be accessed before initialization in vendor/cjrasmussen/bluesky-api/src/BlueskyApi.php:89
```

The problem is this code in `BlueskyApi::refreshSession()`:

```php
$this->apiKey = $api_key;
$data = $this->request('POST', 'com.atproto.server.refreshSession');
unset($this->apiKey);
```

Instead of unsetting `$apiKey`, I think you'll just want to set it back to its initial value of `null` like this:

```php
$this->apiKey = $api_key;
$data = $this->request('POST', 'com.atproto.server.refreshSession');
$this->apiKey = null;
```

**Comment by cjrasmussen** [comment]
You are absolutely correct.  This is resolved in v2.0.3.  Thanks for the heads-up.
