### ISSUE TITLE
Array error on populateLastResponseHeader

### ISSUE THREAD

**Issue by japafrite** [cjrasmussen/BlueskyApi#13]
Hello,

On line 233 with
` [$header_name, $header_value] = array_map('trim', explode(':', $header, 2));
`
I have array error because $header response is without ":" as separator : 
"HTTP/1.1 200 OK\r\n"

**Comment by cjrasmussen** [comment]
I think I designed this wrong anyway. BlueskyApi shouldn't be worried about parsing the header, just providing access to it.  I'm going to update this to return all of the header data as a string, which can then be parsed as necessary outside of the BlueskyApi class.

**Comment by cjrasmussen** [comment]
This change has been implemented as v2.2.0.
