### ISSUE TITLE
Error BlobTooLarge

### ISSUE THREAD

**Issue by dapehe94** [cjrasmussen/BlueskyApi#14]
Hello
When I try to upload images with
`$response = $connection->request(‘POST’, ‘com.atproto.repo.uploadBlob’, [], $body, $mime);
`
I always get this error...
`object(stdClass)#1715 (2) { ["error"]=> string(12) "BlobTooLarge" ["message"]=> string(70) "This file is too large. It is 1.47MB but the maximum size is 976.56KB." }`
Is there any size limitation for images in BlueSky?
Thanks

**Comment by cjrasmussen** [comment]
As I understand it, the limit is not consistent. What I've run up against is 976560 bytes but I can't say for certain that it's a hard limit for every situation.

**Comment by dapehe94** [comment]
Thank you @cjrasmussen 
I don't understand it either, but I can't post link cards :-(
If I try with smaller images, I can do it without any problems...

**Comment by cjrasmussen** [comment]
I dug back through some of my implementation code and that's the specific scenario I ran into as well.  My fix was to iterate over the image, saving it using `imagejpeg` with a lower and lower `quality` until it was under the limit.  Not ideal but it works.
