### ISSUE TITLE
Posting a message with an attachement. access forbidden by rule

### ISSUE THREAD

**Issue by teklynk** [cjrasmussen/BlueskyApi#15]
Hello. I have a strange issue. I created a php function to send a news article to Bluesky. The article contains a thumbnail image and a breif summary/plain text. This works fine from my local dev environment. When I try it from a production server it does not work. The nginx logs show `access forbidden by rule` error. I am using a bluesky handle and app password. Here is my code. I wonder if you have any ideas.

```php
function share_bluesky($thumbnail = null, $msg)
{
 
    $bluesky = new BlueskyApi();

    try {
        $bluesky->auth(getenv('BLUESKY_HANDLE'), getenv('BLUESKY_APP_PASSWORD'));
    } catch (Exception $e) {
        flashMessageSet('danger', 'Something went wrong! Was not able to post message to Bluesky. Error: ' . $e);
        return false;
    }

    $info = pathinfo($thumbnail);
    $extension = $info['extension'];
    $body = file_get_contents($thumbnail);
    $response = $bluesky->request('POST', 'com.atproto.repo.uploadBlob', [], $body, 'image/png');
    $image = $response->blob;

    $args = [
        'collection' => 'app.bsky.feed.post',
        'repo' => $bluesky->getAccountDid(),
        'record' => [
            'text' => $msg,
            'langs' => ['en'],
            'createdAt' => date('c'),
            '$type' => 'app.bsky.feed.post',
            'embed' => [
                '$type' => 'app.bsky.embed.images',
                'images' => [
                    [
                        'alt' => '',
                        'image' => $image,
                    ],
                ],
            ],
        ],
    ];
    
    if (is_array($args) && empty($args)) {
        
        flashMessageSet('danger', 'Something went wrong! Was not able to post message to Bluesky. Error: $args array is empty');
        return false;
    }

    $response = $bluesky->request('POST', 'com.atproto.repo.createRecord', $args);

    flashMessageSet('success', 'News article has been posted to Bluesky');
    return true;
 
}
```

**Comment by teklynk** [comment]
I think the issue is that I am exceeding the 300 character limits. 

Another issue....
'text' => $msg contains a link and tags however, the link and tags are not clickable when posted to Bluesky. Your example shows 'text' => 'Testing #TestingInProduction' which contains a tag. I assumed Bluesky would see that and convert it to a clickable link but it does not. Bluesky just displays the link and tags as plain text.

Do you know how properly display links and tags? I am guessing that you need to parse the message and extract the link uri and tags. Those then get added as part of the embed object? Most other platforms like Mastodon just simply display links and tags as clickable, no problem, no parsing, no extra work. It is confusing to me why Bluesky would do it differently.

**Comment by cjrasmussen** [comment]
Yes, you have to explicitly define what text should be linked and what text should be a hashtag.  That example was documented before Bluesky supported hashtags.  I'm going to update the examples to account for that.

**Comment by cjrasmussen** [comment]
The README has been updated with hashtag and link examples in v2.3.1
