### ISSUE TITLE
Retrieving replies to posts 

### ISSUE THREAD

**Issue by colin-walker** [cjrasmussen/BlueskyApi#4]
I know the scope of this is limited but do you know if it can used/modified to retrieve replies to posts?

I'm coming up against a brick wall so far.

**Comment by cjrasmussen** [comment]
It looks like you'd need to pass the parent post URI to `app.bsky.feed.getPostThread`.  It looks like this in my test:

```
$args = [
	'uri' => 'at://did:plc:k34dbu5i4firbhoyhvrljlf4/app.bsky.feed.post/3jzo4rsusmn2y',
];
$response = $bluesky->request('GET', 'app.bsky.feed.getPostThread', $args);
```

For the record, there is an unofficial Discord for discussing doing stuff with the Bluesky API and the AT protocol, though the PHP section is really quiet.

https://discord.com/channels/1097580399187738645/1100721113702608999

(The last question asked there eventually became #1 as I wasn't in that community at the time.)
